version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Bucharest"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    
    groups:
      spring-dependencies:
        patterns:
          - "org.springframework.*"
      testing-libraries:
        patterns:
          - "org.junit.*"
          - "org.mockito.*"
          - "org.testcontainers.*"

    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Bucharest"
    labels:
      - "ci"
      - "automated-pr"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "docker"