spring.application.name=AuthenticationSpringBoot

# H2 Database Configuration

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-session-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# database
spring.datasource.url=jdbc:postgresql://localhost:5432/blablacar
spring.datasource.username=my_user
spring.datasource.password=my_password

# OAuth2 Configuration
# Note: Replace these with actual values from Google Developer Console
#spring.security.oauth2.client.registration.google.client-id=your-google-client-id
#spring.security.oauth2.client.registration.google.client-secret=your-google-client-secret
#spring.security.oauth2.client.registration.google.scope=email,profile

# Logging Configuration
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.web=DEBUG

logging.level.com.example.blablacar=DEBUG

# ===============================
# = Spring Dev Tools
# ===============================
spring.devtools.restart.enabled=true

# Server Configuration
server.port=8080
