-- Complete review-lifecycle support on databases that received older baselines before V7.
-- Additive only: add identity generation for new review rows and finish lifecycle columns.
-- Reviews are written through the application API; no fixture rows are inserted here.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
            AND table_name = 'user_reviews'
            AND column_name = 'id'
            AND is_identity = 'YES'
    ) THEN
        ALTER TABLE user_reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

ALTER TABLE user_reviews ALTER COLUMN target_user_id DROP NOT NULL;
ALTER TABLE user_reviews ALTER COLUMN reviewer_id DROP NOT NULL;
ALTER TABLE user_reviews ALTER COLUMN details DROP NOT NULL;
ALTER TABLE user_reviews ALTER COLUMN details TYPE varchar(1000);
ALTER TABLE user_reviews ALTER COLUMN date DROP NOT NULL;

ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS reviewer_name varchar(64);
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS status varchar(20);
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS reviewer_role varchar(20);
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS latest_shared_ride_id bigint;
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS latest_shared_dropoff_at timestamptz;
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS window_ends_at timestamptz;
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS submitted_at timestamptz;
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS published_at timestamptz;
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS published_score integer;
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS published_details varchar(1000);
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS published_role varchar(20);
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS hidden_at timestamptz;
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS hidden_reason varchar(200);
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE user_reviews ADD COLUMN IF NOT EXISTS created_at timestamptz;

UPDATE user_reviews
SET status = 'PUBLISHED',
    published_score = score,
    published_details = details,
    published_at = COALESCE(published_at, now()),
    updated_at = COALESCE(updated_at, now())
WHERE status IS NULL;

ALTER TABLE user_reviews ALTER COLUMN status SET DEFAULT 'PENDING';
ALTER TABLE user_reviews ALTER COLUMN status SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uc_user_review_pair ON user_reviews (reviewer_id, target_user_id);

-- The directional pair is already constrained by Hibernate's legacy table-level unique
-- constraint in databases that received the older baseline, so only drop the duplicate
-- when both artifacts exist.

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ukehmpjvq8xyy4vaobxhrxun36g'
            AND conrelid = 'user_reviews'::regclass
    )
    AND EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'public'
            AND tablename = 'user_reviews'
            AND indexname = 'uc_user_review_pair'
    ) THEN
        ALTER TABLE user_reviews DROP CONSTRAINT ukehmpjvq8xyy4vaobxhrxun36g;
    END IF;
END $$;
